NFWWS-7688: Redirect data class type changes
SchwarzIT/andcouchbaseentity pull request #64
Opened 2022-10-11 17:38 UTC by mpradzin

- It can occur, that in case of database changes the cast of the inferred types within the read and write operations are backfiring. To prevent that case, these inconsistencies are recognized and the thrown exception is redirected to the PersistenceConfig
- Adjusted Couchbase2Connector and TypeConversion to be able to handle nullable values and omit NullpointerException in Demo Project
- Changed the statement as safe-cast which is generated in the CblFieldHolder, to prevent that values of propierties within subentities are null which would cause another NullpointerException. (e.g. creating subentity via new HashMap and passing keys but not their values)

2022-10-18 13:28 UTC, sbra0902 requested changes

2022-10-18 13:28 UTC, sbra0902 commented on couchbase-entity-api/src/main/java/kaufland/com/coachbasebinderapi/TypeConversionErrorCallback.kt
> +}
Field should be also interesting here

2022-10-28 07:21 UTC, sbra0902 approved these changes

2022-10-28 07:25 UTC, hoschie approved these changes

2022-10-28 07:26 UTC, merged